# Generated by Django 5.1.3 on 2024-12-06 13:48

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='heading', max_length=30)),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='title', max_length=225)),
                ('Description', models.CharField(blank=True, max_length=2000, null=True)),
                ('Image1', models.ImageField(upload_to='uploads/')),
                ('Body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Sluglink', models.CharField(blank=True, max_length=200, null=True)),
                ('Tags', models.CharField(max_length=100)),
                ('CreatedName', models.CharField(max_length=100)),
                ('Create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.category')),
            ],
            options={
                'ordering': ['-Create_at'],
            },
        ),
    ]
