# Generated by Django 5.1.3 on 2024-12-09 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(default=datetime.datetime(2024, 12, 10, 0, 17, 51, 927031))),
            ],
        ),
    ]
