# Generated by Django 5.1.3 on 2024-12-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='Date',
        ),
    ]
