# Generated by Django 5.1.3 on 2024-12-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='Slug',
        ),
    ]
