# Generated by Django 5.1.3 on 2024-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_media_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
