# Generated by Django 5.1.3 on 2024-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_media_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Url',
            field=models.URLField(default='', max_length=500, null=True),
        ),
    ]
