# Generated by Django 5.1.3 on 2024-12-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='Url',
            new_name='Media_Url',
        ),
    ]
