# Generated by Django 5.1.3 on 2024-12-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_url_media_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('Brandmarketposition', models.CharField(max_length=100)),
                ('BrandCorevalue', models.CharField(max_length=500)),
                ('Brandperceive_targetaudience', models.CharField(max_length=100)),
                ('CustomerFeedback', models.CharField(max_length=100)),
                ('BrandPerformence', models.CharField(max_length=500)),
                ('Challenges_Obstacles', models.CharField(max_length=500)),
                ('Brand_Motivation', models.CharField(max_length=500)),
                ('Goals_Achieves', models.CharField(max_length=500)),
                ('Expectations', models.CharField(max_length=500)),
            ],
        ),
    ]
