# Generated by Django 5.1.3 on 2024-12-12 10:03

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInfo',
            fields=[
                ('ExpertiseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ExpertiseName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField(default=datetime.datetime.now)),
                ('JobType', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Experience', models.CharField(max_length=50)),
                ('WorkingHours', models.CharField(max_length=100)),
                ('WorkingDays', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('Vacancy', models.IntegerField(default='')),
                ('DeadLine', models.CharField(max_length=50)),
                ('Sluglink', models.SlugField(null=True, unique=True)),
                ('Active_status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=1)),
            ],
        ),
    ]
