# Generated by Django 5.1.3 on 2024-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_applyform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='Phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
