# Generated by Django 5.1.3 on 2024-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_media_slug_alter_applyform_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='Media_Url',
        ),
        migrations.AddField(
            model_name='media',
            name='Slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='Url',
            field=models.URLField(default='', max_length=300, null=True),
        ),
    ]
