# Generated by Django 5.1.3 on 2024-12-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_article_remove_media_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
