# Generated by Django 5.1.3 on 2024-12-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_applyform_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntalksForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=10)),
                ('Reason_to_connect', models.CharField(max_length=10)),
            ],
        ),
    ]
