# Generated by Django 5.1.3 on 2024-12-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_portfoliopopupsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
