# Generated by Django 5.1.3 on 2024-12-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-Create_at']},
        ),
    ]
